import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CTASection } from "@/components/CTASection";
import { Icon } from "@/components/Icon";
import { PageHero } from "@/components/PageHero";
import { ProjectArt } from "@/components/ProjectArt";
import { getProject, projects } from "@/data/projects";

export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const project = getProject(slug); return project ? { title: `${project.title} — Case Study`, description: project.summary, alternates: { canonical: `/portfolio/${slug}` } } : {}; }

export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const project = getProject(slug); if (!project) notFound(); const related = projects.filter((item) => item.slug !== slug).slice(0, 2);
  return <><PageHero eyebrow={project.category} trail="Portfolio" title={project.title} text={project.summary} /><section className="project-feature"><div className="container"><ProjectArt project={project} large /><div className="project-facts"><span><small>Client</small>{project.client}</span><span><small>Category</small>{project.category}</span><span><small>Year</small>{project.year}</span><span><small>Tools</small>{project.tools.join(", ")}</span></div></div></section><section className="section"><div className="container case-study"><div><p className="eyebrow">Project overview</p><h2>A concept designed to communicate with confidence.</h2></div><div><h3>The challenge</h3><p>{project.challenge}</p><h3>Design approach</h3><p>{project.approach}</p><h3>Creative solution</h3><p>{project.solution}</p></div></div></section><section className="section section-tint"><div className="container gallery-grid"><ProjectArt project={project} /><div className="gallery-detail"><span>TYPOGRAPHY / COLOUR / GRID</span><b>Aa</b><div>{project.palette.map((colour) => <i key={colour} style={{ background: colour }} />)}</div><small>{project.palette.join(" · ")}</small></div><div className="gallery-lines"><strong>{project.title}</strong><span /><span /><span /><span /></div></div></section><section className="section"><div className="container split-lists"><div><p className="eyebrow">Deliverables</p><ul>{project.deliverables.map((item) => <li key={item}>{item}</li>)}</ul></div><div><p className="eyebrow">Concept results</p><ul>{project.results.map((item) => <li key={item}>{item}</li>)}</ul></div></div><p className="placeholder-note centered">This is a fictional placeholder case study. Results describe the intended design outcomes, not measured client performance.</p></section><section className="section section-tint"><div className="container"><div className="section-heading"><div><p className="eyebrow">More work</p><h2>Related projects</h2></div></div><div className="related-grid">{related.map((item) => <Link href={`/portfolio/${item.slug}`} key={item.slug}><span>{item.category}</span><h3>{item.title}</h3><span>View case study <Icon name="arrow-right" size={16} /></span></Link>)}</div></div></section><CTASection /></>;
}
